source 'https://rubygems.org'


gem 'rails', '4.2.6'
gem 'rails-api'
gem 'spring', :group => :development
gem 'sqlite3'
gem "koala", "~> 2.2"
gem "paperclip", "~> 5.0.0"
gem 'rack-cors', :require => 'rack/cors'
gem 'whenever', :require => false

# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
#
group :test do
  gem 'rspec-rails', '~> 3.0'
end

group :development, :test do
  gem 'dotenv-rails'
  gem "pry-byebug"
end
